name: build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - uses: actions/checkout@v2
      with:
        path: main
    - run: nuget restore TanukiColiseum.sln
      working-directory: main
    - uses: microsoft/setup-msbuild@v1
    - run: msbuild /t:"restore;clean;rebuild" /p:Configuration=Release /p:Platform="Any CPU"
      timeout-minutes: 5
      working-directory: main
    - run: |
        copy LICENSE TanukiColiseum\bin\Release\
        copy *.md TanukiColiseum\bin\Release\
        copy *.sfen TanukiColiseum\bin\Release\
      working-directory: main
    - id: datetime
      run: |
        echo "::set-output name=str::$(Get-Date -Format yyyyMMdd.hhmmss)"
    - uses: actions/upload-artifact@v3
      with:
          name: TanukiColiseum.${{ steps.datetime.outputs.str }}
          path: main\TanukiColiseum\bin\Release\
